### ISSUE TITLE
Version of Python and libraies

### ISSUE THREAD

**Issue by CarinaXZZ** [ratishsp/data2text-plan-py#1]
Hi,
Thanks for the code and the paper.
For the preprocess.py, it has a FileNotFoundError for 'roto.train.1.pt' occurs in line 113(torch.save(dataset,pt_file).
Could you please help me take a look at this?
Thanks.

**Comment by ratishsp** [comment]
Python version is 2.7 and Pytorch version is 0.3.1
Once you run preprocess.py, it will generate the .pt files. The process is similar to training a model on [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py)

**Comment by CarinaXZZ** [comment]
yes, i think used the same version with you.. but it failed to generate the .pt files.
The error is listed as follow:

Extracting features...
 * number of source features- stage 1: 3.
 * number of target features- stage 1: 0.
 * number of source features- stage 2: 3.
 * number of target features- stage 2: 0.
Building `Fields` object...
Building & saving training data...
Warning. The corpus /home/zx16649/data2text/data2text-plan-py/boxscore-data/rotowire/src_train.txt is larger than 10M bytes, you can set '-max_shard_size' to process it by small shards to use less memory.
('average src size', 606, 3371)
 * saving train data shard to ~/boxscore-data/preprocess/roto.train.1.pt.
Traceback (most recent call last):
  File "preprocess.py", line 210, in <module>
    main()
  File "preprocess.py", line 200, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "preprocess.py", line 140, in build_save_dataset
    corpus_type, opt, pointers=pointers)
  File "preprocess.py", line 113, in build_save_text_dataset_in_shards
    torch.save(dataset, pt_file)
  File "/home/zx16649/.local/lib/python2.7/site-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zx16649/.local/lib/python2.7/site-packages/torch/serialization.py", line 115, in _with_file_like
    f = open(f, mode)
IOError: [Errno 2] No such file or directory: '/home/zx16649/data2text/data2text-plan-py/boxscore-data/preprocess/roto.train.1.pt'

**Comment by ratishsp** [comment]
You need to create the folder /home/zx16649/data2text/data2text-plan-py/boxscore-data/preprocess

**Comment by CarinaXZZ** [comment]
it works, thanks
