### ISSUE TITLE
Use which type of data to calculate BLEU? Content plan or summary?

### ISSUE THREAD

**Issue by LarryLee-BD** [ratishsp/data2text-plan-py#10]
Hi Ratish,
Seems the code doesn't contain BLEU part. I have problems about how to calculate BLEU. I used the BLEU tools and inputed gold summaries and generate summaries, and got very high BLEU scores(about 40). 
I also tried content plan tuples files,  and got high scores too(about 32).

**Comment by LarryLee-BD** [comment]
thanks

**Comment by ratishsp** [comment]
I used bleu perl script from https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl
The model summary is used to compute BLEU.
The command I used is 
`~/multi-bleu.perl ~/gold/val.summary < ~/gen/model-output-summary`

**Comment by LarryLee-BD** [comment]
Nice
