### ISSUE TITLE
environment config for running extractor.lua?

### ISSUE THREAD

**Issue by LTlitong** [ratishsp/data2text-plan-py#12]
Hi, thanks for the awesome code and paper !

I got this problem when I run the extractor.lua:   /usr/bin/luajit: /usr/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-4656/cutorch/lib/THC/generic/THCStorage.cu:66

The issue seems to be related to the versions of torch or lua.

So could you please share the running environment config for extractor.lua?

Thanks a lot !

**Comment by ratishsp** [comment]
My cuda version is cuda-8.0.44 and cuDNN version is cuDNN-5.1

**Comment by hwijeen** [comment]
Could you provide more info about the environment?
- Graphic card model
- Nvidia driver version
- lua version
- torch version

Would it be possible that you provide a Dockerfile to run extractor.lua?
I'm having way too much trouble on running it.....
