### ISSUE TITLE
NOT able to find the file 'roto_train-beam5_gens.h5-tuples.txt'

### ISSUE THREAD

**Issue by prakhar1234** [ratishsp/data2text-plan-py#14]
I have downloaded the data from rotowire but not able to find the file name roto_train-beam5_gens.h5-tuples.txt,please guide me the way for it.

**Comment by ratishsp** [comment]
```roto_train-beam5_gens.h5-tuples.txt``` is needed to create the input dataset by running the script ```create_dataset.py```. You may instead download the created dataset at https://drive.google.com/open?id=1R_82ifGiybHKuXnVnC8JhBTW8BAkdwek (this is the same link for dataset in the data2text-plan-py repo)
If you still want to have a look at the ```roto_train-beam5_gens.h5-tuples.txt``` file, you may find it at https://github.com/ratishsp/data2text-1/blob/master/roto_train-beam5_gens.h5-tuples.txt

**Comment by prakhar1234** [comment]
Thanks.
