### ISSUE TITLE
About Accury and Perplexity

### ISSUE THREAD

**Issue by Lightyounger** [ratishsp/data2text-plan-py#15]
Hello, I would like to ask why the accuracy of the results I trained is 0, and I did not change the code. Furthermore, why is the perplexity between the training set and the verification set always the same?

**Comment by JianyuZhao7** [comment]
I wonder why to use ppl as the standard for training, but not RG, CO and so on. Thanks for your kind answers.

**Comment by ratishsp** [comment]
Related issue is #17.
