### ISSUE TITLE
AttributeError: 'Field' object has no attribute 'vocab'

### ISSUE THREAD

**Issue by LemuriaChen** [ratishsp/data2text-plan-py#16]
when i run the stage2, 

BASE=.
MODEL_PATH=$BASE/gen_model/$IDENTIFIER/roto_stage1_acc_73.2760_ppl_2.9340_e9.pt
MODEL_PATH2=$BASE/gen_model/$IDENTIFIER/roto_stage2_acc_57.7477_ppl_7.8817_e24.pt

python translate.py \
	-model $MODEL_PATH \
	-model2 $MODEL_PATH2 \
	-src1 $BASE/rotowire/inf_src_valid.txt \
	-tgt1 $BASE/gen/roto_stage1_$IDENTIFIER-beam5_gens.txt \
	-src2 $BASE/gen/roto_stage1_inter_$IDENTIFIER-beam5_gens.txt \
	-output $BASE/gen/roto_stage2_$IDENTIFIER-beam5_gens.txt \
	-batch_size 10 \
	-max_length 850 \
	-min_length 150 \
	-gpu 0

it reports this error, i don't know why.

**Comment by aim123** [comment]
Hi,
Did you get any solutions for this? i am facing the same issue.

**Comment by ratishsp** [comment]
Google search tells me that the issue could be because of torchtext version incompatibility. Could you confirm if you are using the correct torchtext version torchtext==0.2.3?

**Comment by aim123** [comment]
Hi,
Yes I am using the same version of torchtext.
>>> import torchtext
>>> torchtext.__version__
'0.2.3'
