### ISSUE TITLE
Which metric is used in development?

### ISSUE THREAD

**Issue by JianyuZhao7** [ratishsp/data2text-plan-py#17]
Thanks for your sharing. 
In model training, there are two metric 'ppl' and 'accuracy'. What's more , there are other metrics in evaluation, such as RG, CO and CS.
So which one is used to mentor parameters choosing in development.
Thanks so much

**Comment by ratishsp** [comment]
I have used accuracy metric for model selection. Accuracy had better correlation than perplexity on the validation scores.

**Comment by JianyuZhao7** [comment]
Thanks for your patient answer.&nbsp;
I am a little confused about the 'accuracy'. Is the correct generated words divide ground truth ?&nbsp;
For example, the generated words are 'I am OK' and the ground truth is 'You are OK'. So the accuracy is 2/3≈0.67.
Am I right?
Thanks. &nbsp;




------------------ ------------------



I have used accuracy metric for model selection. Accuracy had better correlation than perplexity on the validation scores.

**Comment by ratishsp** [comment]
Yes, you are correct. The implementation of accuracy computation is at:
https://github.com/ratishsp/data2text-plan-py/blob/d6ac47a1772f99201b0c22c416d0d5ebd5166cb5/onmt/Trainer.py#L44-L45

**Comment by JianyuZhao7** [comment]
thanks so mush
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ratish Puduppully"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 晚上10:10
收件人:&nbsp;"ratishsp/data2text-plan-py"<data2text-plan-py@noreply.github.com&gt;;
抄送:&nbsp;"随风"<912357596@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ratishsp/data2text-plan-py] Which metric is used in development? (#17)




Yes, you are correct. The implementation of accuracy computation is at:
 https://github.com/ratishsp/data2text-plan-py/blob/d6ac47a1772f99201b0c22c416d0d5ebd5166cb5/onmt/Trainer.py#L44-L45

**Comment by JianyuZhao7** [comment]
thanks so much
