### ISSUE TITLE
How to generate the file named "transform_gen/roto-gold-val-beam5_gens.h5-tuples.txt"

### ISSUE THREAD

**Issue by lxsyz** [ratishsp/data2text-plan-py#19]
Hello, thank you so much for sharing your work.

`python non_rg_metrics.py transform_gen/roto-gold-val-beam5_gens.h5-tuples.txt transform_gen/roto_stage1_$IDENTIFIER-beam5_gens.h5-tuples.txt`

I want to ask one question about the file named "transform_gen/roto-gold-val-beam5_gens.h5-tuples.txt". Is it generated by the IE approach? I don't find it in the rotowire directory.

**Comment by ratishsp** [comment]
Hi,
Yes the gold tuples file is generated using IE. It is at https://github.com/ratishsp/data2text-1/blob/master/roto-gold-val.h5-tuples.txt

**Comment by lxsyz** [comment]
OK，Thank you very much
