### ISSUE TITLE
Missing of roto_val-beam5_gens.h5-tuples.txt

### ISSUE THREAD

**Issue by CarinaXZZ** [ratishsp/data2text-plan-py#2]
When I tried to evaluate the accuracy of the first stage, I found that roto_val-beam5_gens.h5-tuples.txt is missing. I assumed that this is the gold tuple file. I wonder if I need to generate by myself. Or I can find it somewhere.

Thanks

**Comment by ratishsp** [comment]
Yes it the gold tuple file. I had got the naming wrong in the README. I will correct the name. The file is https://github.com/ratishsp/data2text-1/blob/master/roto-gold-val.h5-tuples.txt
