### ISSUE TITLE
Load model problems

### ISSUE THREAD

**Issue by lxsyz** [ratishsp/data2text-plan-py#20]
Hello, ratishsp!
I find the code can't load two checkpoint files at the same time. The parameter 'train_from' can pass in only one value. How do you load the checkpoints from the previous training?

**Comment by ratishsp** [comment]
Hi,
I didn't make use of loading checkpoints from previous training. 
Yes, currently the code doesn't support loading two checkpoints. 
You could modify the code in the below lines to achieve loading two checkpoints.:
https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/train.py#L413-L416
