### ISSUE TITLE
wherer i can  get this file.txt？

### ISSUE THREAD

**Issue by rxc205** [ratishsp/data2text-plan-py#24]
hello,where i can get this file :
`ORACLE_IE_OUTPUT = 'roto_train-beam5_gens.h5-tuples.txt'  # oracle content plan obtained from IE tool
`
i want to rep your experiment on my own dataset. i can't produce the dataset due to the lack of the above file.

**Comment by ratishsp** [comment]
Hi,
The file is [here](https://github.com/ratishsp/data2text-1/blob/master/roto_train-beam5_gens.h5-tuples.txt)

**Comment by rxc205** [comment]
ok，thanks :)

**Comment by rxc205** [comment]
when i run :
```
python non_rg_metrics.py \
$BASE/transform_gen/roto-gold-val-beam5_gens.h5-tuples.txt \
$BASE/transform_gen/roto_stage1_$IDENTIFIER-beam5_gens.h5-tuples.txt
```
IOError: [Errno 2] No such file or directory: 'data2text-plan-py/transform_gen/roto-gold-val-beam5_gens.h5-tuples.txt'

My question is  that:
1.  if this file is also == [here](https://github.com/ratishsp/data2text-1/blob/master/roto-gold-val.h5-tuples.txt)
2. how i can generate those file ? another file is same in last week's question:`ORACLE_IE_OUTPUT = 'roto_train-beam5_gens.h5-tuples.txt'  # oracle content plan obtained from IE tool
` ,   are those files all generate by [here](https://github.com/ratishsp/data2text-1)
3. we want to use our own dataset to do some online product research，i just looked your paper, now , it seems not enough.
4.
```
> We extracted content plans from the ROTOWIRE game summaries following an information extraction (IE) approach.
```
dose [this project](https://github.com/ratishsp/data2text-1) means the IE systems?


 I am a little confused, thanks and looking forward to your reply !!!

**Comment by ratishsp** [comment]
1. Yes, the roto-gold-val-beam5_gens.h5-tuples.txt is the one in the https://github.com/ratishsp/data2text-1 repository
2. Yes, the files are generated by running the IE on the gold summaries.
3. I didn't understand this question
> we want to use our own dataset to do some online product research，i just looked your paper, now , it seems not enough.

4. Yes, https://github.com/ratishsp/data2text-1 is the IE system.

**Comment by rxc205** [comment]
0. Ok. you can ingore the question 3, i did't describe clearly.
1. You mean the IE only extract the triples only on the summaries part of raw JSON dataset.  So can i regard those extracted triples(used for generate the input data) as the add information for the raw JSON dataset to extended the data ？
2. have you tried the experiment only use the raw JSON dataset exclude the summary part ?  I mean not use the IE system for summary extraction.

**Comment by ratishsp** [comment]
1. The IE extracts the records after matching the summaries with the input table. Thus the extracted records are a subset of the records in the input table. These extracted records are only used during training. The model learns to extract a sequence of records from input table and to generate the summary conditioned on the linearised records.
During inference, the model first predicts the sequence of records from the input table and then generates the summary.
2. I didn't understand this question.

**Comment by rxc205** [comment]
Ok, i understand. Thanks for your patient reply.
