### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wingedRuslan** [ratishsp/data2text-plan-py#25]
Hi,

I am following steps on the README to reproduce your results. In the **Generation** step, there is a command:
`python scripts/create_content_plan_from_index.py $BASE/rotowire/inf_src_valid.txt $BASE/gen/roto_stage1_$IDENTIFIER-beam5_gens.txt $BASE/transform_gen/roto_stage1_$IDENTIFIER-beam5_gens.h5-tuples.txt  $BASE/gen/roto_stage1_inter_$IDENTIFIER-beam5_gens.txt
`  
and it says to generate the content plan with records from input of content plan with indices.

While running this script, I got the following error:

> IOError: [Errno 2] No such file or directory: data2text-plan-py/boxscore-data/transform_gen/roto_stage1_cc-beam5_gens.h5-tuples.txt'

Is the file *roto_stage1_cc-beam5_gens.h5-tuples.txt'* same as file *roto_train-beam5_gens.h5-tuples.txt* from [here](https://github.com/ratishsp/data2text-1/blob/master/roto_train-beam5_gens.h5-tuples.txt)?

If no, could you please briefly explain how to create the required file?

I run successfully all the steps, but at this point I do not even have a *transform_gen* directory.

Many thanks,
Ruslan

**Comment by ratishsp** [comment]
Hi Ruslan,
The $BASE/transform_gen/roto_stage1_$IDENTIFIER-beam5_gens.h5-tuples.txt file is generated by the scripts/create_content_plan_from_index.py script.
The error you get is because the directory $BASE/transform_gen does not exist. If you will create the directory, the error will go away.

**Comment by wingedRuslan** [comment]
Hi Ratish,

Yes, you are totally right! I missed this tiny detail and could not figure our what the issue was. 

Thanks for the prompt reply!

ps. a note for other researches - when running the *scripts/create_dataset.py*, there is the same error (File missing), solution would be the same - manually create the directory 'inter'  so that while running the script will be able to create a file there - 'rotowire/inter/train_content_plan.txt'
