### ISSUE TITLE
Understanding train-roto-ptrs.txt file

### ISSUE THREAD

**Issue by wingedRuslan** [ratishsp/data2text-plan-py#26]
Hi Ratish,

Thanks a lot for the insightful research paper as well as making the codebase publicly available! I was able to train the model on *boxscore-data* and then used it for inference. Now I am interested in training your model on *my dataset* and then use it for text generation.

Unfortunately, I encountered a problem with the following step (from the README page): 

> The **train-roto-ptrs.txt file** is available along with the dataset and can also be created by the following command: 
> > python data_utils.py -mode ptrs -input_path $BASE/rotowire/train.json -train_content_plan $BASE/rotowire/inter/train_content_plan.txt -output_fi $BASE/rotowire/train-roto-ptrs.txt

Since my dataset is different from *boxscore-data*, I basically have to perform transformations manually to my dataset in order to have it in a suitable format for model training.  

1) "The input dataset for data2text-plan-py can be created by running the script create_dataset.py in scripts folder."    

I have successfully prepared my dataset in the same format as files in *boxscore-data/rotowire/*, namely, the following files: src_train.txt, train_content_plan.txt, tgt_train.txt, inter/train_content_plan.txt and src_valid.txt, tgt_valid.txt, valid_content_plan.txt, inter/valid_content_plan.txt and test/src_test.txt , test/tgt_test.txt. The structure of these files is the same as in files obtained from *boxscore-data*

2) [Preprocessing] I could not run preprocess.py script, since to run this script I need **train-roto-ptrs.txt** file. 

The function for creating this file is:
https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/data_utils.py#L574

Because I have another dataset, I can not use the above-mentioned function, thus I need to create **train-roto-ptrs.txt** file by myself. Unfortunately, going multiple times through the function implementation and analyzing the content of a file (_please see comments_), I could not figure out how to create such file from my dataset. 

Can you please elaborate on the **purposes** of the **train-roto-ptrs.txt** file and briefly **describe the steps** on how it was created? 

This is my current bottleneck and I would highly appreciate your help with this issue! 

Many thanks in advance,
Ruslan

**Comment by wingedRuslan** [comment]
### Analyzing the content of a file

Looking into the content of the original **train-roto-ptrs.txt** file did not help to understand how the file was created.  

![image](https://user-images.githubusercontent.com/14000852/106043033-2124d400-60de-11eb-9a8b-8f4272bc44af.png)
  
From my perspective they are not related to any other information from other files:  

![image](https://user-images.githubusercontent.com/14000852/106043729-1d458180-60df-11eb-8694-0c90d202c080.png)

![image](https://user-images.githubusercontent.com/14000852/106043784-2b939d80-60df-11eb-8be9-e314c00f9110.png)



@ratishsp, Could you please help me to figure out how  the **train-roto-ptrs.txt** file was created?

**Comment by ratishsp** [comment]
Hi Ruslan,
Glad to know that you find the paper and code useful!
The logic for train-roto-ptrs.txt is in method https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/data_utils.py#L574
The core idea is to provide supervision while training the copy mechanism.  https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/onmt/modules/CopyGenerator.py#L199
The entries in the train_roto_ptrs.txt contain mapping between the summary token and the corresponding matching token in the content plan. For eg: the last entry 245,39 in train_roto_ptrs[1] indicates that the 245th token in summary matches with 39th content plan entry.

Having said that, in later experiments I have realized that such supervision is not strictly required. The model learns an accurate value of `p_copy` even without such a supervision.
Hence I would recommend that you could comment out any code which uses the supervision through pointers and the model should work well enough.

**Comment by wingedRuslan** [comment]
Hi Ratish,

Thanks a lot for your prompt answer! 

It was such a useful and valuable comment, that I was able to create same file but now for other dataset! 
> The entries in the train_roto_ptrs.txt contain mapping between the summary token and the corresponding matching token in the content plan. For eg: the last entry 245,39 in train_roto_ptrs[1] indicates that the 245th token in summary matches with 39th content plan entry.

At this moment I did not try to comment out any code which uses the supervision through pointers, since I want to keep things just the way you did! Later I plan to run such an experiment and see whether such supervision is required or not.

**Comment by ratishsp** [comment]
Great!
All the best.

**Comment by happycjksh** [comment]
When I drive the utils_data.py, the terminal output that the index out of range in the line 593. Do you have the problem?
