### ISSUE TITLE
how do you generate the file "roto_train-beam5_gens.h5-tuples.txt"

### ISSUE THREAD

**Issue by yangshuodelove** [ratishsp/data2text-plan-py#27]
Hi,
Thanks for the excellent paper and code. 
(1) What is the purpose of the file "roto_train-beam5_gens.h5-tuples.txt"?
(2) How do you generate it?
(3) If I use other datasets, how to generate files like it?

Thank you very much.

**Comment by yangshuodelove** [comment]
I found it was too hard for me to understand the code step by step without the background knowledge of OpenNMT. Should I understand the code of the model part first or learn OpenNMT in advance? Could you give me some advice?

**Comment by ratishsp** [comment]
Hi @yangshuodelove Thanks for the feedback!
(1) What is the purpose of the file "roto_train-beam5_gens.h5-tuples.txt"?
-The file is needed to provide training supervision to the content planner.
(2) How do you generate it?
-We generate it using an Information Extraction approach by mapping summary with the input table, identifying matching entities and values, and predicting the type of record.
(3) If I use other datasets, how to generate files like it?
-You may use similar IE or string matching techniques to generate such supervision.

**Comment by ratishsp** [comment]
> I found it was too hard for me to understand the code step by step without the background knowledge of OpenNMT. Should I understand the code of the model part first or learn OpenNMT in advance? Could you give me some advice?

Yes, it is advantageous to have background of OpenNMT in advance.
The code of this repo is based on a much older (0.1) version of OpenNMT. The link is https://github.com/OpenNMT/OpenNMT-py/tree/v0.1

**Comment by yangshuodelove** [comment]
Thank you very much. @ratishsp
