### ISSUE TITLE
Training Failed

### ISSUE THREAD

**Issue by wingedRuslan** [ratishsp/data2text-plan-py#28]
Hi Ratish,

Thanks to your comments I was able to create all the required files (from another dataset) for **preprocess.py** script. After running this script, in the folder *preprocess* I have 3 files: roto.train.1.pt, roto.valid.1.pt, roto.vocab.pt. 

These files are used as input to the model training. Unfortunately, running _train.py_ fails, with the following error: 
> RuntimeError: weight tensor should be defined either for all 14 classes or no classes but got weight tensor of shape: [606] at /pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:44

Have you encountered such an error while you were running your experiments? 

I understand, that the error is related to *training_dataset --> OpenNMT --> pytorch*. But since I can successfully execute code on *boxscore-dataset*, I think that the problem is still with my _data_preparation_ steps (Basically I want to create input files *.pt for the model but from another dataset.). 
Are there special requirements for the **format/structure** of the dataset? 

I just made sure that files like *src_trian.txt, tgt_train.txt, train_content_plan.txt* look identical as files obtained after running *create_datasets.py* script. Is there smth I need to take care of additionally ?

I would highly appreciate your help on this issue, since after extensive debugging I still could not figure out the problem!

Many thanks in advance!
Ruslan

```
(data2text_plan_py) ruslan_yermakov@ip-10-123-133-120:~/reproducibility/data2text-plan-py$ python train.py -data $BASE/preprocess/roto -save_model $BASE/gen_model/$IDENTIFIER/roto -encoder_type1 mean -decoder_type1 pointer -enc_layers1 1 -dec_layers1 1 -encoder_type2 brnn -decoder_type2 rnn -enc_layers2 2 -dec_layers2 2 -batch_size 5 -feat_merge mlp -feat_vec_size 600 -word_vec_size 600 -rnn_size 600 -seed 1234 -start_checkpoint_at 4 -epochs 25 -optim adagrad -learning_rate 0.15 -adagrad_accumulator_init 0.1 -report_every 100 -copy_attn -truncated_decoder 100 -gpuid $GPUID -attn_hidden 64 -reuse_copy_attn -start_decay_at 4 -learning_rate_decay 0.97 -valid_batch_size 5
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longermaintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be foundat https://pip.pypa.io/en/latest/development/release-process/#python-2-support
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longermaintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be foundat https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Experiment 22-4.4 using attn_dim of 64
Loading train dataset from /home/ruslan_yermakov/reproducibility/data2text-plan-py/new_dataset/preprocess/roto.train.1.pt, number of examples: 1000
 * vocabulary size. source1 = 4660; target1 = 105, source2 = 4658; target2 = 7382
 * src feature 0 size = 3
 * src feature 1 size = 22
 * src feature 2 size = 4
Building model...
Intializing model parameters.
Intializing model parameters.
NMTModel(
  (encoder): MeanEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(4660, 600, padding_idx=1)
          (1): Embedding(3, 600, padding_idx=1)
          (2): Embedding(22, 600, padding_idx=1)
          (3): Embedding(4, 600, padding_idx=1)
        )
        (mlp): Sequential(
          (0): Linear(in_features=2400, out_features=600, bias=True)
          (1): ReLU()
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (attn): GlobalSelfAttention(
      (transform_in): Sequential(
        (0): Linear(in_features=600, out_features=64, bias=True)
        (1): ELU(alpha=0.1)
      )
      (linear_in): Linear(in_features=64, out_features=64, bias=False)
      (linear_out): Linear(in_features=1200, out_features=600, bias=False)
      (sm): Softmax()
      (tanh): Tanh()
      (dropout): Dropout(p=0.3)
    )
  )
  (decoder): PointerRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(105, 600, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): LSTM(600, 600, dropout=0.3)
    (attn): PointerAttention(
      (linear_in): Linear(in_features=600, out_features=600, bias=False)
      (sm): LogSoftmax()
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=600, out_features=105, bias=True)
    (1): LogSoftmax()
  )
)
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(4658, 600, padding_idx=1)
          (1): Embedding(3, 600, padding_idx=1)
          (2): Embedding(22, 600, padding_idx=1)
          (3): Embedding(4, 600, padding_idx=1)
        )
        (mlp): Sequential(
          (0): Linear(in_features=2400, out_features=600, bias=True)
          (1): ReLU()
        )
      )
    )
    (rnn): LSTM(600, 300, num_layers=2, dropout=0.3, bidirectional=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(7382, 600, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1200, 600)
        (1): LSTMCell(600, 600)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=600, out_features=600, bias=False)
      (linear_out): Linear(in_features=1200, out_features=600, bias=False)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): CopyGenerator(
    (linear): Linear(in_features=600, out_features=7382, bias=True)
    (linear_copy): Linear(in_features=600, out_features=1, bias=True)
  )
)
* number of parameters: 8387465
('encoder: ', 5016560)
('decoder: ', 3370905)
* number of parameters: 25738383
('encoder: ', 8582400)
('decoder: ', 17155983)
Making optimizer for training.
Making optimizer for training.
Start training...
 * number of epochs: 25, starting from Epoch 1
 * batch size: 5
Loading train dataset from /home/ruslan_yermakov/reproducibility/data2text-plan-py/new_dataset/preprocess/roto.train.1.pt, number of examples: 1000
Traceback (most recent call last):
  File "train.py", line 454, in <module>
    main()
  File "train.py", line 446, in main
    train_model(model1, model2, fields, optim1, optim2, data_type, model_opt)
  File "train.py", line 256, in train_model
    train_stats, train_stats2 = trainer.train(train_iter, epoch, report_func)
  File "/home/ruslan_yermakov/reproducibility/data2text-plan-py/onmt/Trainer.py", line 181, in train
    report_stats, total_stats2, report_stats2, normalization)
  File "/home/ruslan_yermakov/reproducibility/data2text-plan-py/onmt/Trainer.py", line 350, in _gradient_accumulation
    trunc_size, self.shard_size, normalization, retain_graph=True)
  File "/home/ruslan_yermakov/reproducibility/data2text-plan-py/onmt/Loss.py", line 127, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/home/ruslan_yermakov/reproducibility/data2text-plan-py/onmt/Loss.py", line 219, in _compute_loss
    loss = self.criterion(scores, gtruth)
  File "/home/ruslan_yermakov/anaconda3/envs/data2text_plan_py/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruslan_yermakov/anaconda3/envs/data2text_plan_py/lib/python2.7/site-packages/torch/nn/modules/loss.py", line 170,in forward
    self.ignore_index, self.reduce)
  File "/home/ruslan_yermakov/anaconda3/envs/data2text_plan_py/lib/python2.7/site-packages/torch/nn/functional.py", line 1052, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: weight tensor should be defined either for all 14 classes or no classes but got weight tensor of shape: [606] at /pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:44
(data2text_plan_py) ruslan_yermakov:~/reproducibility/data2text-plan-py$
```

<details>
  <summary>Log of running preprocess.py</h1></summary>

> (data2text_plan_py) ruslan_yermakov:~/reproducibility/data2text-plan-py$ python preprocess.py -train_src1 $BASE/src_train.txt -train_tgt1 $BASE/train_content_plan.txt -train_src2 $BASE/inter/train_content_plan.txt -train_tgt2 $BASE/tgt_train.txt -valid_src1 $BASE/src_valid.txt -valid_tgt1 $BASE/valid_content_plan.txt -valid_src2 $BASE/inter/valid_content_plan.txt -valid_tgt2 $BASE/tgt_valid.txt -save_data $BASE/preprocess/roto -src_seq_length 1000 -tgt_seq_length 1000 -dynamic_dict-train_ptr $BASE/train-roto-ptrs.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longermaintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be foundat https://pip.pypa.io/en/latest/development/release-process/#python-2-support
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longermaintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be foundat https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Extracting features...
 * number of source features- stage 1: 3.
 * number of target features- stage 1: 0.
 * number of source features- stage 2: 3.
 * number of target features- stage 2: 0.
Building `Fields` object...
Building & saving training data...
('average src size', 26, 1000)
 * saving train data shard to /home/ruslan_yermakov/reproducibility/data2text-plan-py/new_dataset/preprocess/roto.train.1.pt.
Building & saving vocabulary...
 * reloading /home/ruslan_yermakov/reproducibility/data2text-plan-py/new_dataset/preprocess/roto.train.1.pt.
 * tgt1 vocab size: 105.
 * tgt2 vocab size: 7382.
 * src1 vocab size: 4660.
 * src1_feat_0 vocab size: 3.
 * src1_feat_1 vocab size: 22.
 * src1_feat_2 vocab size: 4.
 * src2 vocab size: 4658.
 * src2_feat_0 vocab size: 3.
 * src2_feat_1 vocab size: 22.
 * src2_feat_2 vocab size: 4.
Building & saving validation data...
('average src size', 25, 120)
 * saving valid data shard to /home/ruslan_yermakov/reproducibility/data2text-plan-py/new_dataset/preprocess/roto.valid.1.pt.
(data2text_plan_py) ruslan_yermakov:~/reproducibility/data2text-plan-py$

</details>

**Comment by wingedRuslan** [comment]
I tried to investigate the error, namely, I was figuring out why the weight tensor is of shape [606]  
> RuntimeError: weight tensor should be defined either for all 14 classes or no classes but got weight tensor of shape: [606] at /pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:44

In onmt/Loss.py there is a hard-coded value of *606* for TGT_VOCAB_SIZE  (~maximum size of the target vocabulary), which has a default value *50000* (according to OpenNMT)
https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/onmt/Loss.py#L15

@ratishsp, could you please let me know whether you hard-coded this value for the variable? If yes, how did you choose such a value for the max size of target vocabulary?

Later, the weight vector is created of this size, which strongly relates to the Error I have, while running *train.py*
https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/onmt/Loss.py#L181

**Comment by ratishsp** [comment]
Hi Ruslan,
In my data2text project, the dataset RotoWire has total of 606 records. That is the reason I set the TGT_VOCAB_SIZE as 606. The Pointer Network points to one of the 606 input records. 
In the second stage of summary generation, the weight is set to the output vocabulary of summary text.
Assuming you too have a two stage setup, you may need to change the weight in the NLLLoss criterion accordingly.
https://github.com/ratishsp/data2text-plan-py/blob/4b7453530f570aefe036292f1219bbcf8851ad9f/onmt/Loss.py#L180-L185
