### ISSUE TITLE
Focus only on text generation

### ISSUE THREAD

**Issue by wingedRuslan** [ratishsp/data2text-plan-py#31]
Hi @ratishsp,

Thanks a lot for your continuous support of the project! I still plan to apply your model in my research paper (soon I will write an update on #28) on the dataset different from RotoWire.

From your paper: 

> (a) content selection and planning - operates on the input records of a database and produces a content plan specifying which records are to be verbalized in the document and in which order
> (b) text generation produces the output text given the content plan as input; at each decoding step, the generation model attends over vector representations of the records in the content plan

In my case, there is **no** need to have an explicit plan specifying both what to say and in which order. Basically, I want to use all input records and these records are already ordered according to their location in the target summary. In my case, the (training) content plan is exactly the same as the input. So ideally the model at stage1 should be *identity function* (since content plan same as training data).

For text generation (model at stage2), you use the encoder-decoder architecture with an attention mechanism (encode - BiLSTM, decoder - LSTM with copy mechanism). 

Is it correct to say that in my data2text scenario, I only use the encoder-decoder architecture part by leveraging your implemented data2text model? In this case, would encoder-decoder architecture with an attention mechanism be a sufficient approach for data2text generation? Is there something I am missing?   

Looking forward to your reply :)

Many thanks in advance,
Ruslan

**Comment by ratishsp** [comment]
> Is it correct to say that in my data2text scenario, I only use the encoder-decoder architecture part by leveraging your implemented data2text model? In this case, would encoder-decoder architecture with an attention mechanism be a sufficient approach for data2text generation? Is there something I am missing?

Yes, you can use an encoder-decoder with attention model for your scenario. You may use the latest release of [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) or [fairseq](https://github.com/pytorch/fairseq) for the same.
