### ISSUE TITLE
the length of train.json is different from train_content_plan.txt

### ISSUE THREAD

**Issue by happycjksh** [ratishsp/data2text-plan-py#34]
when I drive the data_utils.py, the Terminal output that the list out of range. I find that the length of train.json is different from train_content_plan.txt. I guess the reason is that the two files have different lengths. Am I right? Can you tell me how to solve the problem?

**Comment by ratishsp** [comment]
This issue is being tracked in https://github.com/ratishsp/data2text-plan-py/issues/8
