### ISSUE TITLE
How to generate the content selection in a more difficult scenario?

### ISSUE THREAD

**Issue by happycjksh** [ratishsp/data2text-plan-py#35]
I have a dataset that also needs content selection. But the table values don't match with summary tokens. For example, in the table, the value is "4993 million", but in the summary, the value is expressed as 2.5 billion.  In the scenario, I can't use string matching to generate content selection and planning. Could you give me some advice about the problem?

**Comment by ratishsp** [comment]
The copy mechanism will work in an exact string match. In other cases, the model will attend on the table and predict from the output vocabulary.
