### ISSUE TITLE
version of pyxdameraulevenshtein

### ISSUE THREAD

**Issue by shubhamagarwal92** [ratishsp/data2text-plan-py#4]
I installed it using `pip install pyxdameraulevenshtein`

However, I am facing this ValueError:

```
  File "non_rg_metrics.py", line 2, in <module>
    from pyxdameraulevenshtein import normalized_damerau_levenshtein_distance
  File "__init__.pxd", line 918, in init pyxdameraulevenshtein
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by ratishsp** [comment]
I am not sure why you get this error. There is ValueError when the module is not able to parse the input. What is the input that you provide? Is it not a number word such as one, two etc?

**Comment by shubhamagarwal92** [comment]
Umm.. its not able to import the package. That is why I am asking the version, in fact the requirements for [data2text](https://github.com/ratishsp/data2text-1) repo.

**Comment by shubhamagarwal92** [comment]
Apparently, they released an updated version 1.5.2 which requires numpy 1.16.1

**Comment by ratishsp** [comment]
I could share with you the version I have locally with me.

**Comment by shubhamagarwal92** [comment]
I got this running for now. Will let you know if I face any more issues. Thanks :)
