### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED problem when running extractor.lua for retraining convolutional extraction model

### ISSUE THREAD

**Issue by LarryLee-BD** [ratishsp/data2text-plan-py#6]
Hi~Need some help here. When retraining convolution IE model using extractor.lua, I met Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED (cudnnSetConvolutionNdDescriptor)
I wonder whether is cuda version problem. I currently uses CUDA 9.0 and CUDNN 5. I try CUDA8.0 and CUDA7.5, still can't work. Error info:

Found Environment variable CUDNN_PATH = /home/work/cudnn/cudnn_v5/cuda/lib64/libcudnn.so.5
epoch	1	lr:	0.7
~/torch/install/bin/lua: .../torch/install/share/lua/5.2/nn/Container.lua:67:
In 3 module of nn.Sequential:
In 2 module of nn.ConcatTable:
In 1 module of nn.Sequential:
.../torch/install/share/lua/5.2/cudnn/init.lua:162: Error in CuDNN: CUDNN_STATUS_NOT_SUPPORTED (cudnnSetConvolutionNdDescriptor)

Thanks

**Comment by ratishsp** [comment]
I am unsure about this issue.
You are trying to train your own IE models?
If you need pretrained IE models you could obtain it from links mentioned in https://github.com/ratishsp/data2text-1/
