### ISSUE TITLE
Train JC model 

### ISSUE THREAD

**Issue by shubhamagarwal92** [ratishsp/data2text-plan-py#9]
Hi Ratish,

AFAIK, this code runs the model with NCP+CC using the flag "-copy_attn". What is the significance of this reuse flag "-reuse_copy_attn"?

How do I train the model with NCP+JC?

**Comment by ratishsp** [comment]
-reuse_copy_attn reuses the model attention as the copy attention following Pointer Generator in See et al.
The code for NCP+JC is similar to NCP+CC with changes mainly in CopyGenerator.py using joint normalization over both prediction over vocabulary and copying from input.
I will try finding the code changes on my machine but it will take some time.
